on:
  push:
    branches:
      - master
name: Publish SAM to AWS
jobs:
  deploy:
    name:  Package 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
     # Python unit test
    - name: Install Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Lambda/requirements.txt
        pip install moto boto3
    - name: Unittest visitor counter Lambda
      run: python Lambda/pythontest.py
    
    #Package
    - name: Package
      uses: chriscoffee/sam-github-actions@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
      with:
        args: package --s3-bucket ${{ secrets.S3_BUCKET }} --output-template-file packaged.yaml
    
    #Deploy
    - name: Deploy
      uses: chriscoffee/sam-github-actions@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        STACK_NAME: ${{ secrets.STACK_NAME }}
      with:
        args: deploy --template-file packaged.yaml --stack-name ${{ secrets.STACK_NAME }} --capabilities CAPABILITY_IAM